import '@/styles/globals.css';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import { MoralisProvider } from 'react-moralis';
import Navbar from '@/components/Navbar/Navbar';
import { ApolloClient, ApolloProvider, InMemoryCache } from '@apollo/client';

const client = new ApolloClient({
	cache: new InMemoryCache(),
	uri: 'https://api.studio.thegraph.com/query/36860/dev-marketplace/v0.0.3',
});

export default function App({ Component, pageProps }: AppProps) {
	return (
		<div style={{ minHeight: '100vh' }}>
			<Head>
				<title>NFTMarketplace</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<MoralisProvider initializeOnMount={false}>
				<ApolloProvider client={client}>
					<Navbar />
					<Component {...pageProps} />
				</ApolloProvider>
			</MoralisProvider>
		</div>
	);
}
